/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UploadAttachmentOptions model module.
 * @module model/UploadAttachmentOptions
 * @version 8.2.7
 */
class UploadAttachmentOptions {
    /**
     * @member {String} base64Contents
     * @type {String}
     */
    base64Contents;
    /**
     * @member {String} contentType
     * @type {String}
     */
    contentType;
    /**
     * @member {String} filename
     * @type {String}
     */
    filename;

    

    /**
     * Constructs a new <code>UploadAttachmentOptions</code>.
     * Options for uploading files for attachments. When sending emails with the API that require attachments first upload each attachment. Then use the returned attachment ID in your &#x60;SendEmailOptions&#x60; when sending an email. This way you can use attachments multiple times once they have been uploaded.
     * @alias module:model/UploadAttachmentOptions
     */
    constructor() { 
        
        UploadAttachmentOptions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UploadAttachmentOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UploadAttachmentOptions} obj Optional instance to populate.
     * @return {module:model/UploadAttachmentOptions} The populated <code>UploadAttachmentOptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UploadAttachmentOptions();

            if (data.hasOwnProperty('base64Contents')) {
                obj['base64Contents'] = ApiClient.convertToType(data['base64Contents'], 'String');
            }
            if (data.hasOwnProperty('contentType')) {
                obj['contentType'] = ApiClient.convertToType(data['contentType'], 'String');
            }
            if (data.hasOwnProperty('filename')) {
                obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
            }
        }
        return obj;
    }
}



export default UploadAttachmentOptions;

